Revert "BC: Auto connect to all group members"
This reverts commit de7374a5d9291d7ad856ec57da053139c7dedac0.

vendor/qcom/opensource/commonsys/packages/apps/Bluetooth/src/com/android/bluetooth/btservice/PhonePolicy.java:45: error: package com.android.bluetooth.groupclient does not exist
import com.android.bluetooth.groupclient.GroupService;
                                        ^
1 error

* Well... com.android.bluetooth.groupclient.GroupService exists in BSP but isn't public. This is the first time they used import instead of calling/accessing it via ReflectionUtils.getRequiredClass

Change-Id: I0383f5c2555aeacdaf73ce60cbbc02eb087de4fc