Revert "CC: Synchronize Call answering between BT, MM and Telephony(2/2)"
src/com/android/bluetooth/btservice/ActiveDeviceManager.java:47: error: package com.android.bluetooth.cc does not exist
import com.android.bluetooth.cc.CCService;
1 error

 * depends on proprietary classes

This reverts commit 05793d54703f5e40339d0bf17cfd4cca5f5b684d.

Change-Id: I017ff58b16ad16fd079617f90e99e32f0e736a64